# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_YCP42WyWcDSNaDey4Iyd97vtuz7I-9
"""

def add(n1,n2):
  return (n1+n2)
