# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IcWUqnSqurPKEO7QoEXx5UTvskIC9RXX
"""

def divide():
  n=int(input('enter divident:'))
  m=int(input('enter divisor:'))
  division=n/m
  return(division)