# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IcWUqnSqurPKEO7QoEXx5UTvskIC9RXX
"""

def divide(j,k):
  division=n/m
  return(division)
